### ISSUE TITLE
--develop doesn't work with isolated_build if setup.py has dependencies in pyproject.toml

### ISSUE THREAD

**Issue by Cadair** [tox-dev/tox#1595]
I have made this test project: https://github.com/Cadair/toxtester which is the minimal project I can make to reproduce this. It contains a `setup.py` file which imports `extension_helpers`, which is listed as a dependency in `pyproject.toml`.

For the first run this works fine:
`$ tox -rvv --develop`

<details>

```
using tox.ini: /tmp/test_tox/tox.ini (pid 1097085)
  removing /tmp/test_tox/.tox/log
using tox-3.14.2 from /home/stuart/.virtualenvs/clean/lib/python3.8/site-packages/tox/__init__.py (pid 1097085)
skipping sdist step
test start: getenv /tmp/test_tox/.tox/test
test cannot reuse: -r flag
test recreate: /tmp/test_tox/.tox/test
/home/stuart/.virtualenvs/clean/bin/python3.8 (/home/stuart/.virtualenvs/clean/bin/python3.8) is {'executable': '/home/stuart/.virtualenvs/clean/bin/python3.8', 'name': 'python', 'version_info': [3, 8, 2, 'final', 0], 'version': '3.8.2 (default, Apr 27 2020, 15:53:34) \n[GCC 9.3.0]', 'is_64': True, 'sysplatform': 'linux'}
test uses /home/stuart/.virtualenvs/clean/bin/python3.8
  removing /tmp/test_tox/.tox/test
setting PATH=/tmp/test_tox/.tox/test/bin:/home/stuart/.virtualenvs/clean/bin:/usr/lib/ccache/bin/:/home/stuart/.cargo/bin:/home/stuart/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stuart/.config/bin:/home/stuart/.local/bin:/home/stuart/Git/riot/riot-web/electron_app/dist/linux-unpacked/
[1097092] /tmp/test_tox/.tox$ /home/stuart/.virtualenvs/clean/bin/python3.8 -m virtualenv --no-download --python /home/stuart/.virtualenvs/clean/bin/python3.8 test
Already using interpreter /home/stuart/.virtualenvs/clean/bin/python3.8
Using base prefix '/usr'
New python executable in /tmp/test_tox/.tox/test/bin/python3.8
Also creating executable in /tmp/test_tox/.tox/test/bin/python
Installing setuptools, pip, wheel...
done.
test installdeps: pytest
setting PATH=/tmp/test_tox/.tox/test/bin:/home/stuart/.virtualenvs/clean/bin:/usr/lib/ccache/bin/:/home/stuart/.cargo/bin:/home/stuart/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stuart/.config/bin:/home/stuart/.local/bin:/home/stuart/Git/riot/riot-web/electron_app/dist/linux-unpacked/
[1097100] /tmp/test_tox$ /tmp/test_tox/.tox/test/bin/python -m pip install pytest
Collecting pytest
  Using cached https://files.pythonhosted.org/packages/9f/f3/0a83558da436a081344aa6c8b85ea5b5f05071214106036ce341b7769b0b/pytest-5.4.3-py3-none-any.whl
Collecting pluggy<1.0,>=0.12
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting wcwidth
  Using cached https://files.pythonhosted.org/packages/1b/7b/de30a3962d8fbebbf8d748bfbf20c05c0a7c495df6716e82af109143ba00/wcwidth-0.2.3-py2.py3-none-any.whl
Collecting py>=1.5.0
  Using cached https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl
Collecting attrs>=17.4.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting packaging
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0
  Using cached https://files.pythonhosted.org/packages/06/b1/2dcadc4861c505a807d5c6d88928450fe5afcf352f205432572a10d74657/more_itertools-8.3.0-py3-none-any.whl
Collecting six
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Installing collected packages: pluggy, wcwidth, py, attrs, six, pyparsing, packaging, more-itertools, pytest
Successfully installed attrs-19.3.0 more-itertools-8.3.0 packaging-20.4 pluggy-0.13.1 py-1.8.1 pyparsing-2.4.7 pytest-5.4.3 six-1.15.0 wcwidth-0.2.3
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
test finish: getenv /tmp/test_tox/.tox/test after 4.77 seconds
test start: developpkg /tmp/test_tox
test develop-inst: /tmp/test_tox
write config to /tmp/test_tox/.tox/test/.tox-config1 as '3fe2b9781ccb82b2a143cdcac2630ff25a74e049d5f34d6c10edd0598ccb705f /home/stuart/.virtualenvs/clean/bin/python3.8\n3.14.2 0 1 0\n00000000000000000000000000000000 pytest'
setting PATH=/tmp/test_tox/.tox/test/bin:/home/stuart/.virtualenvs/clean/bin:/usr/lib/ccache/bin/:/home/stuart/.cargo/bin:/home/stuart/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stuart/.config/bin:/home/stuart/.local/bin:/home/stuart/Git/riot/riot-web/electron_app/dist/linux-unpacked/
[1097106] /tmp/test_tox$ /tmp/test_tox/.tox/test/bin/python -m pip install --exists-action w -e .
Obtaining file:///tmp/test_tox
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.16
  Using cached https://files.pythonhosted.org/packages/cf/5d/e8198f11dd73a91f7bde15ca88a2b78913fa2b416ae2dc2a6aeafcf4c63d/numpy-1.18.4-cp38-cp38-manylinux1_x86_64.whl
Installing collected packages: numpy, toxtester
  Running setup.py develop for toxtester
Successfully installed numpy-1.18.4 toxtester
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
test finish: developpkg /tmp/test_tox after 4.97 seconds
test start: envreport 
setting PATH=/tmp/test_tox/.tox/test/bin:/home/stuart/.virtualenvs/clean/bin:/usr/lib/ccache/bin/:/home/stuart/.cargo/bin:/home/stuart/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stuart/.config/bin:/home/stuart/.local/bin:/home/stuart/Git/riot/riot-web/electron_app/dist/linux-unpacked/
[1097123] /tmp/test_tox$ /tmp/test_tox/.tox/test/bin/python -m pip freeze >.tox/test/log/test-0.log
test finish: envreport  after 0.21 seconds
test installed: attrs==19.3.0,more-itertools==8.3.0,numpy==1.18.4,packaging==20.4,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.7,pytest==5.4.3,six==1.15.0,-e git+git@github.com:Cadair/toxtester.git@5a4d97319920f5cffb3706e0189b6ff576e15f26#egg=toxtester,wcwidth==0.2.3
test start: run-test-pre 
test run-test-pre: PYTHONHASHSEED='1830284512'
test finish: run-test-pre  after 0.00 seconds
test start: run-test 
test run-test: commands[0] | pip freeze
setting PATH=/tmp/test_tox/.tox/test/bin:/home/stuart/.virtualenvs/clean/bin:/usr/lib/ccache/bin/:/home/stuart/.cargo/bin:/home/stuart/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stuart/.config/bin:/home/stuart/.local/bin:/home/stuart/Git/riot/riot-web/electron_app/dist/linux-unpacked/
[1097127] /tmp/test_tox$ /tmp/test_tox/.tox/test/bin/pip freeze
attrs==19.3.0
more-itertools==8.3.0
numpy==1.18.4
packaging==20.4
pluggy==0.13.1
py==1.8.1
pyparsing==2.4.7
pytest==5.4.3
six==1.15.0
-e git+git@github.com:Cadair/toxtester.git@5a4d97319920f5cffb3706e0189b6ff576e15f26#egg=toxtester
wcwidth==0.2.3
test run-test: commands[1] | pytest
setting PATH=/tmp/test_tox/.tox/test/bin:/home/stuart/.virtualenvs/clean/bin:/usr/lib/ccache/bin/:/home/stuart/.cargo/bin:/home/stuart/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stuart/.config/bin:/home/stuart/.local/bin:/home/stuart/Git/riot/riot-web/electron_app/dist/linux-unpacked/
[1097131] /tmp/test_tox$ /tmp/test_tox/.tox/test/bin/pytest
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
cachedir: .tox/test/.pytest_cache
rootdir: /tmp/test_tox
collected 1 item                                                                                                                                                                              

toxtester/test_tox.py .                                                                                                                                                                 [100%]

====================================================================================== 1 passed in 0.11s ======================================================================================
test finish: run-test  after 0.50 seconds
test start: run-test-post 
test finish: run-test-post  after 0.00 seconds
___________________________________________________________________________________________ summary ___________________________________________________________________________________________
  test: commands succeeded
  congratulations :)
```

</details>

However, the second time you run this command (the main reason I want to use `--develop` is to make iterations much faster) it errors while determining if the package needs reinstalling:

`$ tox -vv --develop`

```
using tox.ini: /tmp/test_tox/tox.ini (pid 1097358)
  removing /tmp/test_tox/.tox/log
using tox-3.14.2 from /home/stuart/.virtualenvs/clean/lib/python3.8/site-packages/tox/__init__.py (pid 1097358)
skipping sdist step
test start: getenv /tmp/test_tox/.tox/test
/home/stuart/.virtualenvs/clean/bin/python3.8 (/home/stuart/.virtualenvs/clean/bin/python3.8) is {'executable': '/home/stuart/.virtualenvs/clean/bin/python3.8', 'name': 'python', 'version_info': [3, 8, 2, 'final', 0], 'version': '3.8.2 (default, Apr 27 2020, 15:53:34) \n[GCC 9.3.0]', 'is_64': True, 'sysplatform': 'linux'}
test uses /home/stuart/.virtualenvs/clean/bin/python3.8
test reusing: /tmp/test_tox/.tox/test
test finish: getenv /tmp/test_tox/.tox/test after 0.09 seconds
test start: developpkg /tmp/test_tox
[1097366] /tmp/test_tox$ /tmp/test_tox/.tox/test/bin/python setup.py --name
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from extension_helpers import get_extensions
ModuleNotFoundError: No module named 'extension_helpers'
ERROR: invocation failed (exit code 1)
test finish: developpkg /tmp/test_tox after 0.15 seconds
___________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   test: InvocationError for command /tmp/test_tox/.tox/test/bin/python setup.py --name (exited with code 1)
```

I am happy to work on a patch for this, but I can't find any obvious way to replicate `setup.py --name` with pip etc. Would the best solution be to make the `setup.py --name` check work in the `.package` environment? Or would it be acceptable to just skip the reinstall check if both `isolated_build=True` and `--develop` are passed?

**Comment by gaborbernat** [comment]
IMHO the fix here is to append ``pyproject.toml`` into the ``deps`` section in case of ``--develop`` environments. You can do this manually in the meantime yourself for a quick fix.

**Comment by Cadair** [comment]
I am not sure I fully understand your workaround. Can you do that conditionally on the presence of `--develop`?

**Comment by gaborbernat** [comment]
@Cadair no you could not make it conditional, however, I don't think it would hurt doing it unconditionally.

**Comment by Cadair** [comment]
My main reservation with that is that it ends up making the test environment where the tests are run different from what happens if someone installs the dist. I.e. if you install that test repo you only need `extension_helpers` to build the dist not to run the installed dist. (unless I am thinking about this wrong)

I realise this is probably not that important most of the time, but I would like to be able to keep the separation in an ideal world. Also it triggers my don't repeat yourself alarm :rofl:

**Comment by gaborbernat** [comment]
I was talking about the workaround. Naturally, it's not perfect. The actual solution short-term is to: 

> append `pyproject.toml` into the `deps` section in case of `--develop` environments

In longer-term would self fix once PEP-517 editable installs are a thing.

**Comment by Cadair** [comment]
I tried to look through the source to work out how this is done in tox at the moment, but does tox just call out to `pip` to do the non-editable 517 builds or does it setup it's own isolated env?

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox/blob/master/src/tox/session/__init__.py#L206 disables the package build for usedevelop; probably what we want as in the time solution is that post configuration process if usedevelop is set use https://github.com/tox-dev/tox/blob/master/src/tox/package/builder/isolated.py#L50 to get the list from pyproject.toml and append it; here https://github.com/tox-dev/tox/blob/master/src/tox/config/__init__.py#L809

**Comment by astrojuanlu** [comment]
@gaborbernat Is this something you plan to address as part of the tox rewrite?

**Comment by gaborbernat** [comment]
Yes and I believe this should already work as of today on the rewrite branch.

**Comment by astrojuanlu** [comment]
I tested the `rewrite` branch with poliastro and I'm getting a handful of unexpected results during the build and the test stages, so I'll wait until you officially declare that tox 4 is in alpha/beta state to start reporting stuff. Thanks @gaborbernat!

**Comment by gaborbernat** [comment]
Fixed on the rewrite branch 👍🏻

**Comment by Cadair** [comment]
I can still reproduce this issue on 4.0.0a6 and also the develop branch.

The output I get is:
```
tox -vvv -e py39 --develop                                                                                                                                                                                   
using tox.ini: /home/stuart/Git/sunpy/tox.ini (pid 14284)
  removing /home/stuart/Git/sunpy/.tox/log
using tox-3.22.0 from /usr/lib/python3.9/site-packages/tox/__init__.py (pid 14284)
skipping sdist step
py39 uses /usr/bin/python
py39 start: getenv /home/stuart/Git/sunpy/.tox/py39
py39 reusing: /home/stuart/Git/sunpy/.tox/py39
py39 finish: getenv /home/stuart/Git/sunpy/.tox/py39 after 0.02 seconds
py39 start: developpkg /home/stuart/Git/sunpy
[14308] /home/stuart/Git/sunpy$ /home/stuart/Git/sunpy/.tox/py39/bin/python setup.py --name
Traceback (most recent call last):
  File "/home/stuart/Git/sunpy/setup.py", line 6, in <module>
    from extension_helpers import get_extensions
ModuleNotFoundError: No module named 'extension_helpers'
ERROR: invocation failed (exit code 1)
py39 finish: developpkg /home/stuart/Git/sunpy after 0.12 seconds
```
